name: Build and Scan APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew
    # - name: Build the app
    #   run: ./gradlew build
    - name: Appknox Scan
      uses: appknox/appknox-github-action@1.0.0
      with:
        appknox_access_token: ${{ secrets.APPKNOX_ACCESS_TOKEN }}
        file_path: apk-binary-code/sample-app.apk
        risk_threshold: HIGH
