name: Build and Scan APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Appknox Scan
      id: appknox-scan
      uses: ashujha301/appknox-github-actions@main
      with:
        appknox_access_token: ${{ secrets.APPKNOX_ACCESS_TOKEN }}
        file_path: apk-binary-code/sample-app.apk
        risk_threshold: MEDIUM

    - name: Display Scan Output
      run: echo "${{ steps.appknox-scan.outputs.scan-output }}"
      
    - name: Generate SARIF Output
      id: sarif-output
      run: echo "${{ steps.appknox-scan.outputs.scan-output }}" | node ./src/tools.js
      shell: bash

    - name: Display SARIF Output
      run: echo "${{ steps.sarif-output.outputs.sarif-output }}"
