name: Build and Scan APK
on:
  push:
    branches:
      - main
permissions:
  security-events: write
  contents: read
  actions: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
    - uses: actions/checkout@v2
      

    - name: Appknox Scan
      id: appknox_scan
      uses: "ashujha301/appknox-github-action@main"
      env:
        ACTIONS_RUNNER_DEBUG: true
      with:
        appknox_access_token: ${{secrets.APPKNOX_ACCESS_TOKEN}}
        file_path: apk-binary-code/sample-app.apk
        risk_threshold: HIGH
        sarif: 'true'

    - name: Upload SARIF report to GitHub code scanning
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: report.sarif
