name: Build and Scan APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
    - uses: actions/checkout@v2

    - name: Set SARIF Environment Variable
      run: echo "SARIF_ENABLED=${{steps.appknox_scan.outputs.sarif}}" >> $GITHUB_ENV

    - name: Appknox Scan
      id: appknox_scan
      uses: "ashujha301/appknox-github-action@main"
      env:
        ACTIONS_RUNNER_DEBUG: true
      with:
        appknox_access_token: ${{secrets.APPKNOX_ACCESS_TOKEN}}
        file_path: apk-binary-code/sample-app.apk
        risk_threshold: MEDIUM
        sarif: 'true'
      continue-on-error: true
    
    - name: Upload SARIF Report
      if: env.SARIF_ENABLED == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: sarif-report
        path: report.sarif.json

    - name: Upload SARIF to GHAS
      if: env.SARIF_ENABLED == 'true'
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: report.sarif.json
